name: Parallel Shell - Terminus Deployment
on: [workflow_dispatch]
jobs:
  build:
    name: Deploy all to LIVE
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   # Install Terminus.
    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Parallel Processing
      run: |
        terminus org:site:list ${ORG_UUID} --format list --upstream ${UPSTREAM_UUID} --field name | sort -V | parallel --jobs 100 .github/scripts/shell/live-deploy.sh {}
        