name: Deploy to Test
on: 
  workflow_dispatch:
    inputs:
      pantheon_tag:
        description: 'Pantheon Tags to deploy to (Defaults to all if empty)'
        required: true
        default: 'all'
env:
  INPUT_PANTHEON_TAG: ${{ github.event.inputs.pantheon_tag }}
jobs:
  build:
    name: Deploy all to TEST
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   # Install Terminus.
    - name: Install and Authorize Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
    - name: Execute Parallel Deployment
      run: |
        if  [ $INPUT_PANTHEON_TAG == all ]
        then
          terminus org:site:list $ORG_UUID --format list --upstream $UPSTREAM_UUID  --tag $INPUT_PANTHEON_TAG --field name | sort -V | parallel --jobs 100 .github/scripts/test-deploy.sh {}
        else
          terminus org:site:list $ORG_UUID --format list --upstream $UPSTREAM_UUID --field name | sort -V | parallel --jobs 100 .github/scripts/test-deploy.sh {}
        fi
